export const CREATE_LIST_FORM = [
	{
		default_value: '',
		key: 'item_name',
		label: 'Item Name',
		mandatory: true,
		option: [],
		type: 'input',
		visibility: true,
	},
	{
		default_value: '',
		key: 'serial_number',
		label: 'Serial Number',
		mandatory: true,
		option: [],
		type: 'input',
		visibility: true,
	},
	{
		default_value: '',
		key: 'purchase_date',
		label: 'Purchase Date',
		mandatory: true,
		option: [],
		type: 'inputDate',
		visibility: true,
	},
	{
		default_value: '',
		key: 'warrenty_valid_till_date',
		label: 'Warrenty Valid Till',
		mandatory: true,
		option: [],
		type: 'inputDate',
		visibility: true,
	},
	{
		default_value: '',
		key: 'price',
		label: 'Price',
		mandatory: true,
		option: [],
		type: 'input',
		visibility: true,
	},
	{
		default_value: '',
		key: 'price_um',
		label: 'Currency',
		mandatory: true,
		option: [],
		type: 'input',
		visibility: true,
	},
	{
		default_value: '',
		key: 'item_brand_name',
		label: 'Brand Name',
		mandatory: true,
		option: [],
		type: 'input',
		visibility: true,
	},
];
