export const RegisterJson = [
	{
		default_value: '',
		key: 'orgnisation_name',
		label: 'Organisation Name',
		mandatory: true,
		option: [],
		sequence: 1,
		switch_default_value: '',
		switch_key: '',
		type: 'inputText',
		validation: [],
		visibility: true,
	},
	{
		default_value: '',
		key: 'contact_num1',
		label: 'Phone Number',
		mandatory: true,
		option: [],
		sequence: 1,
		switch_default_value: '',
		switch_key: '',
		type: 'inputText',
		validation: [],
		visibility: true,
	},
	{
		default_value: '',
		key: 'contact_num2',
		label: 'Phone Number 2',
		mandatory: true,
		option: [],
		sequence: 1,
		switch_default_value: '',
		switch_key: '',
		type: 'inputText',
		validation: [],
		visibility: true,
	},
];
